### ISSUE TITLE
Определиться с дизайном игры 

### ISSUE THREAD

**Issue by Kislichenko** [KSPT-Project-RED/Dominion#3]
Приложить 2 скрина игрового поля для 2х и 4х игроков. Взять с уже готовых реализаций или с youtube/

**Comment by Basta123** [comment]
![Dominion_2Players](https://user-images.githubusercontent.com/24698273/68072379-1f167d00-fd96-11e9-824b-afb83ffed874.png)

![Dominion_4Players](https://user-images.githubusercontent.com/24698273/68072161-6bac8900-fd93-11e9-9199-ffb797ea95ad.png)

игровое поле для двух и четверых игроков будет идентично за исключением, что при четверых игроках на игровом поле будут размещаться дополнительно карты третьего и четвертого игрока (на второй картинке указаны области для размещения карт третьего и четвертого игрока)

**Comment by Kislichenko** [comment]
А что это за игра?

**Comment by Basta123** [comment]
Dominion на PC. https://www.youtube.com/watch?v=YogsWGKymJs и https://www.youtube.com/watch?v=BwqP6mT-dCQ
