### ISSUE TITLE
Составить базу иконок карт и их описания

### ISSUE THREAD

**Issue by Kislichenko** [KSPT-Project-RED/Dominion#4]
В соответствии с описанием карт в правилах (см. выбранные правила https://github.com/KSPT-Project-RED/Dominion/issues/2 ) заходим на https://pixabay.com/ по фильтрам: иллюстрации, цвет -  прозрачный и ищем похожие с картами по правилам картинки. 

Картинки, скачанные с pixabay, НЕ ПЕРЕИМЕНОВЫВАТЬ. Затем, в папке Abilities создаем txt файл с названием скачанной картинки. В этом файле заполняем поля name, ability, cost, attack, hp. В ability пишем способности в соответсвии типами способностей и заклинаний из правил. Все способности нужно будет реализовывать программно, поэтому не пишем жесткую отсебятину и делаем похожие способности (желательно не больше 10 типов).

Пример способностей первого типа (необязательно должен быть именно такой тип):
1) Восстановление на 1 hp соседей
2) Восстановление на 2 hp соседей

Пример способностей второго типа (необязательно должен быть именно такой тип):
1) Удар  одного врага на 1 hp
2) Удар  одного врага на 2 hp

Затем заполняем excel табличку соответствия картинке ссылки на pixabay.
cost, attack, hp заполняются так, чтобы соответствовать хоть как-то балансу по правилам.

Name и картинки (с pixaby) берем любые.
Заполняем по примеру:
[Resources.zip](https://github.com/KSPT-Project-RED/Dominion/files/3797378/Resources.zip)

**Comment by Kislichenko** [comment]
До 15 часов 2 ноября 2019 года должно быть готово МИНИМУМ  2 фракции с минимальным набором карт, чтобы можно было играть

**Comment by Kislichenko** [comment]
https://dominiana.wordpress.com/2012/10/02/all_cards/#dominion
https://tesera.ru/images/items/18407/Dominion_Rules_RU.pdf

**Comment by mrff902** [comment]
[Resources.zip](https://github.com/KSPT-Project-RED/Dominion/files/3908429/Resources.zip)

**Comment by Kislichenko** [comment]
В принципе норм. Пока не закрою, т.к. некоторые картинки, возможно, придется изменить.

**Comment by mrff902** [comment]
Конечно) Только дублируй тогда задачу в диалог, а то я пропустила прошлый раз

**Comment by mrff902** [comment]
Выбери одного, чтоб я вставила 
 
Торговец
+1 карта. +1 действие. В первый раз за этот ход, когда вы играете серебро: +1$
cost: 3

![image](https://user-images.githubusercontent.com/56236940/69921330-bb20ca80-14a1-11ea-954c-35e1829b0da5.png)
1.https://pixabay.com/ru/illustrations/%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B2%D0%B5%D1%86-%D0%BF%D0%BE-%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%B6%D0%B0%D0%BC-%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-3337462/

![image](https://user-images.githubusercontent.com/56236940/69921459-d04a2900-14a2-11ea-819e-150659dcaf7a.png)
2. https://pixabay.com/ru/vectors/%D0%B0%D0%B3%D0%B5%D0%BD%D1%82-%D0%BF%D0%BE-%D0%BD%D0%B5%D0%B4%D0%B2%D0%B8%D0%B6%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8-%D0%B0%D0%B3%D0%B5%D0%BD%D1%82-%D0%B4%D0%BE%D0%BC-28776/

![image](https://user-images.githubusercontent.com/56236940/69921471-e3f58f80-14a2-11ea-9dc2-bce6b3412db3.png)
3. https://pixabay.com/ru/illustrations/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80-%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-1212298/

**Comment by mrff902** [comment]
Браконьер
+1 карта. +1 действие. +1$. Сбросьте карту за каждую пустую стопку в резерве.
cost: 4
![image](https://user-images.githubusercontent.com/56236940/69921616-9a0da900-14a4-11ea-8976-33c63981f147.png)
https://pixabay.com/ru/illustrations/%D0%BE%D1%85%D0%BE%D1%82%D0%BD%D0%B8%D0%BA-%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA-%D1%84%D0%B0%D0%BD%D1%82%D0%B0%D0%B7%D0%B8%D1%8F-%D0%BF%D0%BE%D0%B7%D0%B0-1443648/

Караульный
+1 карта.  +1 действие. Посмотрите 2 верхние карты своей колоды. Вы можете выкинуть на свалку или сбросить любые из просмотренных карт. Оставшиеся карты положите на верх своей колоды в любом порядке.
cost: 5 
![image](https://user-images.githubusercontent.com/56236940/69921749-384e3e80-14a6-11ea-90b7-781cddf740f2.png)
https://pixabay.com/ru/vectors/%D1%84%D0%B0%D0%BD%D1%82%D0%B0%D0%B7%D0%B8%D1%8F-%D0%B0%D1%80%D1%87%D0%B5%D1%80-%D1%87%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA-%D0%BB%D1%83%D0%BA-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BA%D0%B0-2926695/

Вассал
+2$. Сбросьте верхнюю карту своей колоды. Если эта карта действия, вы можете её разыграть. 
cost: 3 

![image](https://user-images.githubusercontent.com/56236940/69921752-4a2fe180-14a6-11ea-8034-9eaf7b828c32.png)
https://pixabay.com/ru/vectors/%D0%BA%D1%80%D0%BE%D0%BB%D0%B8%D0%BA-%D1%85%D0%B0%D1%80%D0%B0%D0%BA%D1%82%D0%B5%D1%80-%D0%B0%D0%BB%D0%B8%D1%81%D0%B0-%D0%B2-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B5-%D1%87%D1%83%D0%B4%D0%B5%D1%81-30751/

**Comment by mrff902** [comment]
[Resources+.zip](https://github.com/KSPT-Project-RED/Dominion/files/3908925/Resources%2B.zip)
