### ISSUE TITLE
Подобрать фон для игры

### ISSUE THREAD

**Issue by Kislichenko** [KSPT-Project-RED/Dominion#44]
Найти _**бесшовный**_ бархатный зеленый фон (как для карточных игр - типо покера, дурака)

**Comment by mrff902** [comment]
![image](https://user-images.githubusercontent.com/56236940/69917129-c6f59800-1473-11ea-9904-6f75ad2188b6.png)

**Comment by mrff902** [comment]
![image](https://user-images.githubusercontent.com/56236940/69917157-0328f880-1474-11ea-8bbf-dc013f276de1.png)
http://resizeme.club/imageresizer-334_18.html

**Comment by mrff902** [comment]
![image](https://user-images.githubusercontent.com/56236940/69917172-3c616880-1474-11ea-82cb-b8c3a62faef0.png)
https://www.liveinternet.ru/users/3092960/post355063844/

**Comment by mrff902** [comment]
https://www.esky.ru/upload/iblock/a2e/veljur_big.jpg 
![image](https://user-images.githubusercontent.com/56236940/69917189-6f0b6100-1474-11ea-8bd3-c05cfd6e632c.png)

http://resizeme.club/imageresizer-334_18.html

**Comment by mrff902** [comment]
![image](https://user-images.githubusercontent.com/56236940/69917200-83e7f480-1474-11ea-9e46-328834b59c2d.png)
![image](https://user-images.githubusercontent.com/56236940/69917211-9b26e200-1474-11ea-8887-06b53e79b215.png)
https://www.pinterest.co.kr/pin/578712620844439267/

**Comment by Kislichenko** [comment]
первые 3 сразу видно, что не бесшовные
